name             'opsworks_elasticsearch'
maintainer       'Adrien Brault'
maintainer_email 'adrien.brault@gmail.com'
license          'MIT'
description      'ElasticSearch OpsWorks'
long_description 'ElasticSearch OpsWorks'
version          '0.1.0'

depends 'elasticsearch'
depends 'java'
