name             'opsworks_kibana'
maintainer       'Adrien Brault'
maintainer_email 'adrien.brault@gmail.com'
license          'MIT'
description      'Kibana OpsWorks'
long_description 'Kibana OpsWorks'
version          '0.1.0'

depends 'opsworks_utils'
depends 'ohai'
depends 'kibana'
